services:
  - type: web
    name: carbonguard-calculator-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --access-logfile - --error-logfile - app:app
